name: Flutter Mobile Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  flutter-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: subosito/flutter-action@f2c4f6686a23884099450d9990e78297b47b4d32 # v2.18.0
        with:
          flutter-version: "3.29.2"
          channel: "stable"
      - run: |
          cd apps/mobile
          flutter pub get
          flutter analyze
          flutter test
