name: IaC Infrastructure Scan

on:
  push:
    branches: [main, build/development-platform]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: bridgecrewio/checkov-action@9b70310bcd306d11740313070b940167d6b23085 # v9
        with:
          framework: dockerfile
          output_format: cli
          soft_fail: true
