name: SBOM Generation

on:
  push:
    branches: [main, build/development-platform]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  sbom-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Anchore/sbom-action@df80a981bc6edbc4e220a492d3cbe9f5547a6e75 # v0.17.9
        with:
          format: cyclonedx-json
          output-file: docs/sbom/cyclonedx.sbom.json
