name: SBOM Generation

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  sbom-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: Anchore/sbom-action@f325610c28d51684c19ad484e6a063806c013d7a # v0.17.9
        with:
          format: spdx-json
          output-file: guffsuff-sbom.spdx.json
